name: Run private main.py (public repo only)

on:
  workflow_dispatch:
    inputs:
      REF:
        description: "Branch/Tag của repo riêng tư"
        required: true
        default: "main"
      FILE_PATH:
        description: "Đường dẫn tới main.py trong repo riêng tư"
        required: true
        default: "src/main.py"
      PYTHON_VERSION:
        description: "Python version để chạy"
        required: true
        default: "3.10"

jobs:
  run-main:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions: {}
    steps:
      - name: Checkout (public repo)
        uses: actions/checkout@v4

      - name: Checkout (private repo, sparse to 1 file)
        uses: actions/checkout@v4
        with:
          repository: your-org-or-user/your-private-repo
          ref: ${{ inputs.REF }}
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: private-src
          fetch-depth: 1
          sparse-checkout: |
            ${{ inputs.FILE_PATH }}
          sparse-checkout-cone: false

      - name: Setup Python ${{ inputs.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install Python deps (requests)
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run main.py từ repo riêng tư
        shell: bash
        run: |
          set -euo pipefail
          FILE="private-src/${{ inputs.FILE_PATH }}"
          if [[ ! -f "$FILE" ]]; then
            echo "::error::Không tìm thấy file: $FILE"
            ls -la private-src || true
            exit 1
          fi
          echo "[INFO] Running: $FILE"
          python "$FILE"
